const bcrypt = require("bcrypt");
const sequelize = require("../config/dbSync");
const Department = require("../models/DepartmentModel");
const Employee = require("../models/employees/EmployeeModel");
const EmployeePayrollDetails = require("../models/employees/EmployeePayrollModel");
const FamilyDetails = require("../models/employees/FamilyDetailsModel");
const WorkExperience = require("../models/employees/WorkExperienceModel");
const Certification = require("../models/employees/CertificationsModel");
const AcademicQualification = require("../models/employees/AcademicQualificationsModel");
const EmployeeContractModel = require("../models/employees/EmployeeContractModel");
const JobPosting = require("../models/JobPostingModel");
const {
  EmployeeContractTemplateModel,
  EmployeeContractDetailsModel,
} = require("../models/ContractModel");
const Attendence = require("../models/AttendenceModel");
const ContractType = require("../models/ContractTypeModel");
const Designation = require("../models/DesignationModel");
const Leavetype = require("../models/LeaveTypeModel");
const Workplace = require("../models/WorkplaceModel");
const BankDetails = require("../models/BankDetailsModel");
const PenaltyType = require("../models/PenaltyTypeModel");
const AirTickets = require("../models/AirTicketModel");
const Payroll = require("../models/PayrollModel");
const LeaveRequest = require("../models/LeaveRequestModel");
const LeaveApproval = require("../models/LeaveApprovalModel");
const Settings = require("../models/SettingsModel");
const Penalty = require("../models/PenaltyModel");
const Commission = require("../models/CommissionModel");
const PerformanceManagement = require("../models/PerformanceManagementModel");
const TrainingAndDevelopment = require("../models/TrainingAndDevelopmentModel");
const Goals = require("../models/GoalModel");
const KPIs = require("../models/KPIModel");
const Countries = require("../models/CountryModel");
const LoanRequest = require("../models/LoanRequestModel");
const LoanApproval = require("../models/LoanApprovalModel");
const Gratuity = require("../models/GratuityModel");
const AnnualLeaveProvision = require("../models/provisions/AnnualLeaveProvisionPolicy");
const AirTicketProvision = require("../models/provisions/AirTicketProvisionPolicy");
const PayrollsDeductions = require("../models/PayrollDeductionModel");
const CertificationBody = require("../models/CertificationBodyModel");
const CertificationName = require("../models/CertificationNameModel");
const CertificationType = require("../models/CertificationTypeModel");
const Industry = require("../models/IndustryModel");
const TrainingDetailsModel = require("../models/TrainingDetailsModel");
const JobOnboardingModel = require("../models/JobOnboardingModel");
const GatePassLocationModel = require("../models/GatePassLocationModel");

const seedDatabase = async (syncOption = { alter: true }) => {
  try {
    // Sync database
    await sequelize.sync(syncOption);
    console.log(`Database synced with ${JSON.stringify(syncOption)}`);

    //-----------------------------------------------------HR Module Seeds------------------------------------------------------------

    // Seed Settings
    const settingsList = [["salaryCalculationDate", new Date()]];

    const settingsData = settingsList.map(([name, value]) => ({
      name,
      value,
    }));

    await Settings.bulkCreate(settingsData, { ignoreDuplicates: true });
    console.log("Settings successfully seeded!");

    // Seed CountryList
    const countryList = [
      ["AF", "Afghanistan", "أفغانستان", "Afghan", "أفغانستاني"],
      ["AL", "Albania", "ألبانيا", "Albanian", "ألباني"],
      ["AX", "Aland Islands", "جزر آلاند", "Aland Islander", "آلاندي"],
      ["DZ", "Algeria", "الجزائر", "Algerian", "جزائري"],
      [
        "AS",
        "American Samoa",
        "ساموا-الأمريكي",
        "American Samoan",
        "أمريكي سامواني",
      ],
      ["AD", "Andorra", "أندورا", "Andorran", "أندوري"],
      ["AO", "Angola", "أنغولا", "Angolan", "أنقولي"],
      ["AI", "Anguilla", "أنغويلا", "Anguillan", "أنغويلي"],
      ["AQ", "Antarctica", "أنتاركتيكا", "Antarctican", "أنتاركتيكي"],
      ["AG", "Antigua and Barbuda", "أنتيغوا وبربودا", "Antiguan", "بربودي"],
      ["AR", "Argentina", "الأرجنتين", "Argentinian", "أرجنتيني"],
      ["AM", "Armenia", "أرمينيا", "Armenian", "أرميني"],
      ["AW", "Aruba", "أروبه", "Aruban", "أوروبهيني"],
      ["AU", "Australia", "أستراليا", "Australian", "أسترالي"],
      ["AT", "Austria", "النمسا", "Austrian", "نمساوي"],
      ["AZ", "Azerbaijan", "أذربيجان", "Azerbaijani", "أذربيجاني"],
      ["BS", "Bahamas", "الباهاماس", "Bahamian", "باهاميسي"],
      ["BH", "Bahrain", "البحرين", "Bahraini", "بحريني"],
      ["BD", "Bangladesh", "بنغلاديش", "Bangladeshi", "بنغلاديشي"],
      ["BB", "Barbados", "بربادوس", "Barbadian", "بربادوسي"],
      ["BY", "Belarus", "روسيا البيضاء", "Belarusian", "روسي"],
      ["BE", "Belgium", "بلجيكا", "Belgian", "بلجيكي"],
      ["BZ", "Belize", "بيليز", "Belizean", "بيليزي"],
      ["BJ", "Benin", "بنين", "Beninese", "بنيني"],
      [
        "BL",
        "Saint Barthelemy",
        "سان بارتيلمي",
        "Saint Barthelmian",
        "سان بارتيلمي",
      ],
      ["BM", "Bermuda", "جزر برمودا", "Bermudan", "برمودي"],
      ["BT", "Bhutan", "بوتان", "Bhutanese", "بوتاني"],
      ["BO", "Bolivia", "بوليفيا", "Bolivian", "بوليفي"],
      [
        "BA",
        "Bosnia and Herzegovina",
        "البوسنة و الهرسك",
        "Bosnian / Herzegovinian",
        "بوسني/هرسكي",
      ],
      ["BW", "Botswana", "بوتسوانا", "Botswanan", "بوتسواني"],
      ["BV", "Bouvet Island", "جزيرة بوفيه", "Bouvetian", "بوفيهي"],
      ["BR", "Brazil", "البرازيل", "Brazilian", "برازيلي"],
      [
        "IO",
        "British Indian Ocean Territory",
        "إقليم المحيط الهندي البريطاني",
        "British Indian Ocean Territory",
        "إقليم المحيط الهندي البريطاني",
      ],
      ["BN", "Brunei Darussalam", "بروني", "Bruneian", "بروني"],
      ["BG", "Bulgaria", "بلغاريا", "Bulgarian", "بلغاري"],
      ["BF", "Burkina Faso", "بوركينا فاسو", "Burkinabe", "بوركيني"],
      ["BI", "Burundi", "بوروندي", "Burundian", "بورونيدي"],
      ["KH", "Cambodia", "كمبوديا", "Cambodian", "كمبودي"],
      ["CM", "Cameroon", "كاميرون", "Cameroonian", "كاميروني"],
      ["CA", "Canada", "كندا", "Canadian", "كندي"],
      ["CV", "Cape Verde", "الرأس الأخضر", "Cape Verdean", "الرأس الأخضر"],
      ["KY", "Cayman Islands", "جزر كايمان", "Caymanian", "كايماني"],
      [
        "CF",
        "Central African Republic",
        "جمهورية أفريقيا الوسطى",
        "Central African",
        "أفريقي",
      ],
      ["TD", "Chad", "تشاد", "Chadian", "تشادي"],
      ["CL", "Chile", "شيلي", "Chilean", "شيلي"],
      ["CN", "China", "الصين", "Chinese", "صيني"],
      [
        "CX",
        "Christmas Island",
        "جزيرة عيد الميلاد",
        "Christmas Islander",
        "جزيرة عيد الميلاد",
      ],
      [
        "CC",
        "Cocos [Keeling] Islands",
        "جزر كوكوس",
        "Cocos Islander",
        "جزر كوكوس",
      ],
      ["CO", "Colombia", "كولومبيا", "Colombian", "كولومبي"],
      ["KM", "Comoros", "جزر القمر", "Comorian", "جزر القمر"],
      ["CG", "Congo", "الكونغو", "Congolese", "كونغي"],
      ["CK", "Cook Islands", "جزر كوك", "Cook Islander", "جزر كوك"],
      ["CR", "Costa Rica", "كوستاريكا", "Costa Rican", "كوستاريكي"],
      ["HR", "Croatia", "كرواتيا", "Croatian", "كوراتي"],
      ["CU", "Cuba", "كوبا", "Cuban", "كوبي"],
      ["CY", "Cyprus", "قبرص", "Cypriot", "قبرصي"],
      ["CW", "Curaçao", "كوراساو", "Curacian", "كوراساوي"],
      ["CZ", "Czech Republic", "الجمهورية التشيكية", "Czech", "تشيكي"],
      ["DK", "Denmark", "الدانمارك", "Danish", "دنماركي"],
      ["DJ", "Djibouti", "جيبوتي", "Djiboutian", "جيبوتي"],
      ["DM", "Dominica", "دومينيكا", "Dominica", "دومينيكي"],
      [
        "DO",
        "Dominican Republic",
        "الجمهورية الدومينيكية",
        "Dominican",
        "دومينيكي",
      ],
      ["EC", "Ecuador", "إكوادور", "Ecuadorian", "إكوادوري"],
      ["EG", "Egypt", "مصر", "Egyptian", "مصري"],
      ["SV", "El Salvador", "إلسلفادور", "Salvadoran", "سلفادوري"],
      [
        "GQ",
        "Equatorial Guinea",
        "غينيا الاستوائي",
        "Equatorial Guinean",
        "غيني",
      ],
      ["ER", "Eritrea", "إريتريا", "Eritrean", "إريتيري"],
      ["EE", "Estonia", "استونيا", "Estonian", "استوني"],
      ["ET", "Ethiopia", "أثيوبيا", "Ethiopian", "أثيوبي"],
      [
        "FK",
        "Falkland Islands [Malvinas]",
        "جزر فوكلاند",
        "Falkland Islander",
        "فوكلاندي",
      ],
      ["FO", "Faroe Islands", "جزر فارو", "Faroese", "جزر فارو"],
      ["FJ", "Fiji", "فيجي", "Fijian", "فيجي"],
      ["FI", "Finland", "فنلندا", "Finnish", "فنلندي"],
      ["FR", "France", "فرنسا", "French", "فرنسي"],
      [
        "GF",
        "French Guiana",
        "غويانا الفرنسية",
        "French Guianese",
        "غويانا الفرنسية",
      ],
      [
        "PF",
        "French Polynesia",
        "بولينيزيا الفرنسية",
        "French Polynesian",
        "بولينيزيي",
      ],
      [
        "TF",
        "French Southern and Antarctic Lands",
        "أراض فرنسية جنوبية وأنتارتيكية",
        "French Southern and Antarctic Lands",
        "أراض فرنسية جنوبية وأنتارتيكية",
      ],
      ["GA", "Gabon", "الغابون", "Gabonese", "غابوني"],
      ["GM", "Gambia", "غامبيا", "Gambian", "غامبي"],
      ["GE", "Georgia", "جيورجيا", "Georgian", "جيورجي"],
      ["DE", "Germany", "ألمانيا", "German", "ألماني"],
      ["GH", "Ghana", "غانا", "Ghanaian", "غاني"],
      ["GI", "Gibraltar", "جبل طارق", "Gibraltar", "جبل طارق"],
      ["GG", "Guernsey", "غيرنزي", "Guernsian", "غيرنزي"],
      ["GR", "Greece", "اليونان", "Greek", "يوناني"],
      ["GL", "Greenland", "جرينلاند", "Greenlandic", "جرينلاندي"],
      ["GD", "Grenada", "غرينادا", "Grenadian", "غرينادي"],
      ["GP", "Guadeloupe", "جزر جوادلوب", "Guadeloupe", "جزر جوادلوب"],
      ["GU", "Guam", "جوام", "Guamanian", "جوامي"],
      ["GT", "Guatemala", "غواتيمال", "Guatemalan", "غواتيمالي"],
      ["GN", "Guinea", "غينيا", "Guinean", "غيني"],
      ["GW", "Guinea-Bissau", "غينيا-بيساو", "Guinea-Bissauan", "غيني"],
      ["GY", "Guyana", "غيانا", "Guyanese", "غياني"],
      ["HT", "Haiti", "هايتي", "Haitian", "هايتي"],
      [
        "HM",
        "Heard and Mc Donald Islands",
        "جزيرة هيرد وجزر ماكدونالد",
        "Heard and Mc Donald Islanders",
        "جزيرة هيرد وجزر ماكدونالد",
      ],
      ["HN", "Honduras", "هندوراس", "Honduran", "هندوراسي"],
      ["HK", "Hong Kong", "هونغ كونغ", "Hongkongese", "هونغ كونغي"],
      ["HU", "Hungary", "المجر", "Hungarian", "مجري"],
      ["IS", "Iceland", "آيسلندا", "Icelandic", "آيسلندي"],
      ["IN", "India", "الهند", "Indian", "هندي"],
      ["IM", "Isle of Man", "جزيرة مان", "Manx", "ماني"],
      ["ID", "Indonesia", "أندونيسيا", "Indonesian", "أندونيسيي"],
      ["IR", "Iran", "إيران", "Iranian", "إيراني"],
      ["IQ", "Iraq", "العراق", "Iraqi", "عراقي"],
      ["IE", "Ireland", "إيرلندا", "Irish", "إيرلندي"],
      ["IL", "Israel", "إسرائيل", "Israeli", "إسرائيلي"],
      ["IT", "Italy", "إيطاليا", "Italian", "إيطالي"],
      ["CI", "Ivory Coast", "ساحل العاج", "Ivory Coastian", "ساحل العاج"],
      ["JE", "Jersey", "جيرزي", "Jersian", "جيرزي"],
      ["JM", "Jamaica", "جمايكا", "Jamaican", "جمايكي"],
      ["JP", "Japan", "اليابان", "Japanese", "ياباني"],
      ["JO", "Jordan", "الاردن", "Jordanian", "أردني"],
      ["KZ", "Kazakhstan", "كازاخستان", "Kazakh", "كازاخستاني"],
      ["KE", "Kenya", "كينيا", "Kenyan", "كيني"],
      ["KI", "Kiribati", "كيريباتي", "I-Kiribati", "كيريباتي"],
      ["KP", "Korea[North Korea]", "كوريا الشمالية", "North Korean", "كوري"],
      ["KR", "Korea[South Korea]", "كوريا الجنوبية", "South Korean", "كوري"],
      ["XK", "Kosovo", "كوسوفو", "Kosovar", "كوسيفي"],
      ["KW", "Kuwait", "الكويت", "Kuwaiti", "كويتي"],
      ["KG", "Kyrgyzstan", "قيرغيزستان", "Kyrgyzstani", "قيرغيزستاني"],
      ["LA", "Lao PDR", "لاوس", "Laotian", "لاوسي"],
      ["LV", "Latvia", "لاتفيا", "Latvian", "لاتيفي"],
      ["LB", "Lebanon", "لبنان", "Lebanese", "لبناني"],
      ["LS", "Lesotho", "ليسوتو", "Basotho", "ليوسيتي"],
      ["LR", "Liberia", "ليبيريا", "Liberian", "ليبيري"],
      ["LY", "Libya", "ليبيا", "Libyan", "ليبي"],
      ["LI", "Liechtenstein", "ليختنشتين", "Liechtenstein", "ليختنشتيني"],
      ["LT", "Lithuania", "لتوانيا", "Lithuanian", "لتوانيي"],
      ["LU", "Luxembourg", "لوكسمبورغ", "Luxembourger", "لوكسمبورغي"],
      ["LK", "Sri Lanka", "سريلانكا", "Sri Lankan", "سريلانكي"],
      ["MO", "Macau", "ماكاو", "Macanese", "ماكاوي"],
      ["MK", "Macedonia", "مقدونيا", "Macedonian", "مقدوني"],
      ["MG", "Madagascar", "مدغشقر", "Malagasy", "مدغشقري"],
      ["MW", "Malawi", "مالاوي", "Malawian", "مالاوي"],
      ["MY", "Malaysia", "ماليزيا", "Malaysian", "ماليزي"],
      ["MV", "Maldives", "المالديف", "Maldivian", "مالديفي"],
      ["ML", "Mali", "مالي", "Malian", "مالي"],
      ["MT", "Malta", "مالطا", "Maltese", "مالطي"],
      ["MH", "Marshall Islands", "جزر مارشال", "Marshallese", "مارشالي"],
      ["MQ", "Martinique", "مارتينيك", "Martiniquais", "مارتينيكي"],
      ["MR", "Mauritania", "موريتانيا", "Mauritanian", "موريتانيي"],
      ["MU", "Mauritius", "موريشيوس", "Mauritian", "موريشيوسي"],
      ["YT", "Mayotte", "مايوت", "Mahoran", "مايوتي"],
      ["MX", "Mexico", "المكسيك", "Mexican", "مكسيكي"],
      ["FM", "Micronesia", "مايكرونيزيا", "Micronesian", "مايكرونيزيي"],
      ["MD", "Moldova", "مولدافيا", "Moldovan", "مولديفي"],
      ["MC", "Monaco", "موناكو", "Monacan", "مونيكي"],
      ["MN", "Mongolia", "منغوليا", "Mongolian", "منغولي"],
      ["ME", "Montenegro", "الجبل الأسود", "Montenegrin", "الجبل الأسود"],
      ["MS", "Montserrat", "مونتسيرات", "Montserratian", "مونتسيراتي"],
      ["MA", "Morocco", "المغرب", "Moroccan", "مغربي"],
      ["MZ", "Mozambique", "موزمبيق", "Mozambican", "موزمبيقي"],
      ["MM", "Myanmar", "ميانمار", "Myanmarian", "ميانماري"],
      ["NA", "Namibia", "ناميبيا", "Namibian", "ناميبي"],
      ["NR", "Nauru", "نورو", "Nauruan", "نوري"],
      ["NP", "Nepal", "نيبال", "Nepalese", "نيبالي"],
      ["NL", "Netherlands", "هولندا", "Dutch", "هولندي"],
      [
        "AN",
        "Netherlands Antilles",
        "جزر الأنتيل الهولندي",
        "Dutch Antilier",
        "هولندي",
      ],
      [
        "NC",
        "New Caledonia",
        "كاليدونيا الجديدة",
        "New Caledonian",
        "كاليدوني",
      ],
      ["NZ", "New Zealand", "نيوزيلندا", "New Zealander", "نيوزيلندي"],
      ["NI", "Nicaragua", "نيكاراجوا", "Nicaraguan", "نيكاراجوي"],
      ["NE", "Niger", "النيجر", "Nigerien", "نيجيري"],
      ["NG", "Nigeria", "نيجيريا", "Nigerian", "نيجيري"],
      ["NU", "Niue", "ني", "Niuean", "ني"],
      [
        "NF",
        "Norfolk Island",
        "جزيرة نورفولك",
        "Norfolk Islander",
        "نورفوليكي",
      ],
      [
        "MP",
        "Northern Mariana Islands",
        "جزر ماريانا الشمالية",
        "Northern Marianan",
        "ماريني",
      ],
      ["NO", "Norway", "النرويج", "Norwegian", "نرويجي"],
      ["OM", "Oman", "سلطنة عمان", "Omani", "عماني"],
      ["PK", "Pakistan", "باكستان", "Pakistani", "باكستاني"],
      ["PW", "Palau", "بالاو", "Palauan", "بالاوي"],
      ["PS", "Palestine", "فلسطين", "Palestinian", "فلسطيني"],
      ["PA", "Panama", "بنما", "Panamanian", "بنمي"],
      [
        "PG",
        "Papua New Guinea",
        "بابوا غينيا الجديدة",
        "Papua New Guinean",
        "بابوي",
      ],
      ["PY", "Paraguay", "باراغواي", "Paraguayan", "بارغاوي"],
      ["PE", "Peru", "بيرو", "Peruvian", "بيري"],
      ["PH", "Philippines", "الفليبين", "Filipino", "فلبيني"],
      ["PN", "Pitcairn", "بيتكيرن", "Pitcairn Islander", "بيتكيرني"],
      ["PL", "Poland", "بولندا", "Polish", "بولندي"],
      ["PT", "Portugal", "البرتغال", "Portuguese", "برتغالي"],
      ["PR", "Puerto Rico", "بورتو ريكو", "Puerto Rican", "بورتي"],
      ["QA", "Qatar", "قطر", "Qatari", "قطري"],
      ["RE", "Reunion Island", "ريونيون", "Reunionese", "ريونيوني"],
      ["RO", "Romania", "رومانيا", "Romanian", "روماني"],
      ["RU", "Russian", "روسيا", "Russian", "روسي"],
      ["RW", "Rwanda", "رواندا", "Rwandan", "رواندا"],
      [
        "KN",
        "Saint Kitts and Nevis",
        "سانت كيتس ونيفس,",
        "Kittitian/Nevisian",
        "سانت كيتس ونيفس",
      ],
      [
        "MF",
        "Saint Martin [French part]",
        "ساينت مارتن فرنسي",
        "St. Martian[French]",
        "ساينت مارتني فرنسي",
      ],
      [
        "SX",
        "Sint Maarten [Dutch part]",
        "ساينت مارتن هولندي",
        "St. Martian[Dutch]",
        "ساينت مارتني هولندي",
      ],
      [
        "LC",
        "Saint Pierre and Miquelon",
        "سان بيير وميكلون",
        "St. Pierre and Miquelon",
        "سان بيير وميكلوني",
      ],
      [
        "VC",
        "Saint Vincent and the Grenadines",
        "سانت فنسنت وجزر غرينادين",
        "Saint Vincent and the Grenadines",
        "سانت فنسنت وجزر غرينادين",
      ],
      ["WS", "Samoa", "ساموا", "Samoan", "ساموي"],
      ["SM", "San Marino", "سان مارينو", "Sammarinese", "ماريني"],
      [
        "ST",
        "Sao Tome and Principe",
        "ساو تومي وبرينسيبي",
        "Sao Tomean",
        "ساو تومي وبرينسيبي",
      ],
      [
        "SA",
        "Saudi Arabia",
        "المملكة العربية السعودية",
        "Saudi Arabian",
        "سعودي",
      ],
      ["SN", "Senegal", "السنغال", "Senegalese", "سنغالي"],
      ["RS", "Serbia", "صربيا", "Serbian", "صربي"],
      ["SC", "Seychelles", "سيشيل", "Seychellois", "سيشيلي"],
      ["SL", "Sierra Leone", "سيراليون", "Sierra Leonean", "سيراليوني"],
      ["SG", "Singapore", "سنغافورة", "Singaporean", "سنغافوري"],
      ["SK", "Slovakia", "سلوفاكيا", "Slovak", "سولفاكي"],
      ["SI", "Slovenia", "سلوفينيا", "Slovenian", "سولفيني"],
      ["SB", "Solomon Islands", "جزر سليمان", "Solomon Island", "جزر سليمان"],
      ["SO", "Somalia", "الصومال", "Somali", "صومالي"],
      ["ZA", "South Africa", "جنوب أفريقيا", "South African", "أفريقي"],
      [
        "GS",
        "South Georgia and the South Sandwich",
        "المنطقة القطبية الجنوبية",
        "South Georgia and the South Sandwich",
        "لمنطقة القطبية الجنوبية",
      ],
      [
        "SS",
        "South Sudan",
        "السودان الجنوبي",
        "South Sudanese",
        "سوادني جنوبي",
      ],
      ["ES", "Spain", "إسبانيا", "Spanish", "إسباني"],
      ["SH", "Saint Helena", "سانت هيلانة", "St. Helenian", "هيلاني"],
      ["SD", "Sudan", "السودان", "Sudanese", "سوداني"],
      ["SR", "Suriname", "سورينام", "Surinamese", "سورينامي"],
      [
        "SJ",
        "Svalbard and Jan Mayen",
        "سفالبارد ويان ماين",
        "Svalbardian/Jan Mayenian",
        "سفالبارد ويان ماين",
      ],
      ["SZ", "Swaziland", "سوازيلند", "Swazi", "سوازيلندي"],
      ["SE", "Sweden", "السويد", "Swedish", "سويدي"],
      ["CH", "Switzerland", "سويسرا", "Swiss", "سويسري"],
      ["SY", "Syria", "الجمهورية العربية السورية", "Syrian", "سوري"],
      ["TW", "Taiwan", "تايوان", "Taiwanese", "تايواني"],
      ["TJ", "Tajikistan", "طاجيكستان", "Tajikistani", "طاجيكستاني"],
      ["TZ", "Tanzania", "تنزانيا", "Tanzanian", "تنزانيي"],
      ["TH", "Thailand", "تايلندا", "Thai", "تايلندي"],
      ["TL", "Timor-Leste", "تيمور الشرقية", "Timor-Lestian", "تيموري"],
      ["TG", "Togo", "توغو", "Togolese", "توغي"],
      ["TK", "Tokelau", "توكيلاو", "Tokelaian", "توكيلاوي"],
      ["TO", "Tonga", "تونغا", "Tongan", "تونغي"],
      [
        "TT",
        "Trinidad and Tobago",
        "ترينيداد وتوباغو",
        "Trinidadian/Tobagonian",
        "ترينيداد وتوباغو",
      ],
      ["TN", "Tunisia", "تونس", "Tunisian", "تونسي"],
      ["TR", "Turkey", "تركيا", "Turkish", "تركي"],
      ["TM", "Turkmenistan", "تركمانستان", "Turkmen", "تركمانستاني"],
      [
        "TC",
        "Turks and Caicos Islands",
        "جزر توركس وكايكوس",
        "Turks and Caicos Islands",
        "جزر توركس وكايكوس",
      ],
      ["TV", "Tuvalu", "توفالو", "Tuvaluan", "توفالي"],
      ["UG", "Uganda", "أوغندا", "Ugandan", "أوغندي"],
      ["UA", "Ukraine", "أوكرانيا", "Ukrainian", "أوكراني"],
      [
        "AE",
        "United Arab Emirates",
        "الإمارات العربية المتحدة",
        "Emirati",
        "إماراتي",
      ],
      ["GB", "United Kingdom", "المملكة المتحدة", "British", "بريطاني"],
      ["US", "United States", "الولايات المتحدة", "American", "أمريكي"],
      [
        "UM",
        "US Minor Outlying Islands",
        "قائمة الولايات والمناطق الأمريكية",
        "US Minor Outlying Islander",
        "أمريكي",
      ],
      ["UY", "Uruguay", "أورغواي", "Uruguayan", "أورغواي"],
      ["UZ", "Uzbekistan", "أوزباكستان", "Uzbek", "أوزباكستاني"],
      ["VU", "Vanuatu", "فانواتو", "Vanuatuan", "فانواتي"],
      ["VE", "Venezuela", "فنزويلا", "Venezuelan", "فنزويلي"],
      ["VN", "Vietnam", "فيتنام", "Vietnamese", "فيتنامي"],
      [
        "VI",
        "Virgin Islands [U.S.]",
        "الجزر العذراء الأمريكي",
        "American Virgin Islander",
        "أمريكي",
      ],
      ["VA", "Vatican City", "فنزويلا", "Vatican", "فاتيكاني"],
      [
        "WF",
        "Wallis and Futuna Islands",
        "والس وفوتونا",
        "Wallisian/Futunan",
        "فوتوني",
      ],
      ["EH", "Western Sahara", "الصحراء الغربية", "Sahrawian", "صحراوي"],
      ["YE", "Yemen", "اليمن", "Yemeni", "يمني"],
      ["ZM", "Zambia", "زامبيا", "Zambian", "زامبياني"],
      ["ZW", "Zimbabwe", "زمبابوي", "Zimbabwean", "زمبابوي"],
    ];

    const countriesData = countryList.map(
      ([
        country_code,
        country_enName,
        country_arName,
        country_enNationality,
        country_arNationality,
      ]) => ({
        country_code,
        country_enName,
        country_arName,
        country_enNationality,
        country_arNationality,
      }),
    );

    await Countries.bulkCreate(countriesData, { ignoreDuplicates: true });
    console.log("Countries successfully seeded!");

    // Seed Department Data
    const departments = [
      {
        departmentNo: 101,
        departmentName: "IT Department",
        departmentDescription:
          "Responsible for managing all IT infrastructure and software development",
        departmentHead: "John Doe",
        location: "Headquarters, Colombo",
        createdBy: "admin",
        status: "Active",
        staffName: "Jane Smith",
      },
      {
        departmentNo: 102,
        departmentName: "HR Department",
        departmentDescription:
          "Handles all human resources tasks including recruitment, payroll, and employee relations",
        departmentHead: "Mary Johnson",
        location: "Headquarters, Colombo",
        createdBy: "admin",
        status: "Active",
        staffName: "David Lee",
      },
      {
        departmentNo: 103,
        departmentName: "Sales Department",
        departmentDescription:
          "Handles sales and customer relationship management",
        departmentHead: "Robert Brown",
        location: "Headquarters, Colombo",
        createdBy: "admin",
        status: "Active",
        staffName: "Emily Davis",
      },
    ];

    await Department.bulkCreate(departments, { ignoreDuplicates: true });
    console.log("Departments successfully seeded!");

    // Seed data for 1st employee
    const sampleEmployees = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0001",
          fullNameEnglish: "John Doe",
          fullNameArabic: "جون دو",
          qidNumber: 123456,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "john.doe@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "John Doe",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 23121,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC123456789",
          issuingAuthority: "Qatar Health Ministry",
          expireDate: "2025-12-31",
          knownMedicalConditions: "None",
          allergies: "Peanuts",
          notesOrRemarks: "Requires annual check-up",
          policyNumber: "POL123456",
          coverageDetails: "Comprehensive medical and dental coverage",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Doha Insurance",
          additionalPolicyDetails: "Includes emergency evacuation",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Forklift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-06",
          gatePassNumber: "GP789045",
          gatePassLocation: "Doha",
          gateAccessNo: "1, 12",
          appHashNumber: "App808706",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ799979",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Office",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 6,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees, { ignoreDuplicates: true });
    console.log("Employees 1 successfully seeded!");

    // Seed data for 2nd employee
    const sampleEmployees2 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0002",
          fullNameEnglish: "Alan Taylor",
          fullNameArabic: "جون دو",
          qidNumber: 232532,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "alan.taylor@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "John Doe",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees2, { ignoreDuplicates: true });
    console.log("Employees 2 successfully seeded!");

    // Seed data for 3rd employee
    const sampleEmployees3 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0003",
          fullNameEnglish: "Mathew Jackson",
          fullNameArabic: "جون دو",
          qidNumber: 785432,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "mathew.jackson@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "Mathew Jackson",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees3, { ignoreDuplicates: true });
    console.log("Employees 3 successfully seeded!");

    // Seed data for 4th employee
    const sampleEmployees4 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0004",
          fullNameEnglish: "William Smith",
          fullNameArabic: "جون دو",
          qidNumber: 678686,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "william.smith@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "William Smith",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees4, { ignoreDuplicates: true });
    console.log("Employees 4 successfully seeded!");

    // Seed data for 5th employee
    const sampleEmployees5 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0005",
          fullNameEnglish: "Thomas Anderson",
          fullNameArabic: "جون دو",
          qidNumber: 7599457,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "thomas.anderson@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "William Smith",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees5, { ignoreDuplicates: true });
    console.log("Employees 5 successfully seeded!");

    // Seed data for familyDetails
    const familyDetails = [
      {
        name: "Jane Doe",
        emergencyContactNumber: "+97467895432",
        emergencyName: "Jane Doe",
        emergencyRelationship: "Spouse",
        numberOfFamilyMembers: 3,
        familyInQatar: false,
        relationship: "Wife",
        dob: "1992-05-10",
        qidNo: 789654123,
        qidExpiry: "2026-12-31",
        passportNo: "X9876543",
        passportExpiry: "2027-01-15",
        location: "Qatar",
        airTicket: true,
        insurance: true,
        schoolBenefit: false,
        employeeId: 2,
      },
      {
        name: "Jack Doe",
        emergencyContactNumber: "+97467895432",
        emergencyName: "Jane Doe",
        emergencyRelationship: "Spouse",
        numberOfFamilyMembers: 3,
        familyInQatar: false,
        relationship: "Son",
        dob: "2015-08-22",
        qidNo: 789654124,
        qidExpiry: "2026-12-31",
        passportNo: "X9876544",
        passportExpiry: "2027-03-10",
        location: "Qatar",
        airTicket: true,
        insurance: true,
        schoolBenefit: true,
        employeeId: 2,
      },
      {
        name: "Emma Doe",
        emergencyContactNumber: "+97467895432",
        emergencyName: "Jane Doe",
        emergencyRelationship: "Spouse",
        numberOfFamilyMembers: 3,
        familyInQatar: false,
        relationship: "Daughter",
        dob: "2018-03-15",
        qidNo: 789654125,
        qidExpiry: "2026-12-31",
        passportNo: "X9876545",
        passportExpiry: "2027-04-20",
        location: "Qatar",
        airTicket: true,
        insurance: true,
        schoolBenefit: true,
        employeeId: 2,
      },
    ];

    await FamilyDetails.bulkCreate(familyDetails, { ignoreDuplicates: true });
    console.log("Family Details successfully seeded!");

    // Seed data for Payroll for 1st employee
    const payrollDetails1 = [
      {
        basicSalary: 5200,
        accommodationAllowance: "fullPackageAllowance",
        foodAllowance: "fullPackageFoodAllowance",
        transportationAllowance: "fullPackageTransportationAllowance",
        nationalAccreditationBonus: 250,
        natureOfWorkAllowance: 350,
        socialBonus: 200,
        relocationAllowance: 600,
        otherBonuses: 120,
        overTimeApplicable: false,
        otRate: 0,
        startDate: "2025-01-01",
        endDate: "2025-12-31",
        fullPackageAllowance: 2200,
        fullPackageFoodAllowance: 950,
        fullPackageTransportationAllowance: 850,
        totalSalary: 11200,
        status: "Active",
        employeeId: 1,
      },
    ];

    await EmployeePayrollDetails.bulkCreate(payrollDetails1, {
      ignoreDuplicates: true,
    });
    console.log("Payroll Details 1 successfully seeded!");

    // Seed data for Payroll for 2nd employee
    const payrollDetails2 = [
      {
        basicSalary: 5200,
        accommodationAllowance: "fullPackageAllowance",
        foodAllowance: "fullPackageFoodAllowance",
        transportationAllowance: "fullPackageTransportationAllowance",
        nationalAccreditationBonus: 250,
        natureOfWorkAllowance: 350,
        socialBonus: 200,
        relocationAllowance: 600,
        otherBonuses: 120,
        overTimeApplicable: false,
        otRate: 0,
        startDate: "2025-01-01",
        endDate: "2025-12-31",
        fullPackageAllowance: 2200,
        fullPackageFoodAllowance: 950,
        fullPackageTransportationAllowance: 850,
        totalSalary: 11200,
        status: "Active",
        employeeId: 2,
      },
    ];

    await EmployeePayrollDetails.bulkCreate(payrollDetails2, {
      ignoreDuplicates: true,
    });
    console.log("Payroll Details 2 successfully seeded!");

    // Seed Academic Qualifications
    const qualify = [
      {
        qualification: "Bachelor of Science",
        qualificationType: "Degree",
        year: "2015",
        location: "Doha, Qatar",
        employeeId: 1,
      },
      {
        qualification: "Master of Business Administration",
        qualificationType: "Postgraduate",
        year: "2018",
        location: "London, UK",
        employeeId: 1,
      },
      {
        qualification: "PhD in Computer Science",
        qualificationType: "Doctorate",
        year: "2022",
        location: "Boston, USA",
        employeeId: 1,
      },
    ];

    await AcademicQualification.bulkCreate(qualify, { ignoreDuplicates: true });
    console.log("Academic Qualification Details successfully seeded!");

    // Seed Certifications
    const certify = [
      {
        certificationType: "Professional",
        certificationName: "Certified ScrumMaster",
        otherYear: "2023",
        otherLocation: "Doha, Qatar",
        certificationExpireDate: "2025-12-31",
        certificationBody: "Scrum Alliance",
        documents: null,
        employeeId: 1,
      },
      {
        certificationType: "Technical",
        certificationName: "AWS Certified Solutions Architect",
        otherYear: "2022",
        otherLocation: "London, UK",
        certificationExpireDate: "2025-06-30",
        certificationBody: "Amazon Web Services",
        documents: null,
        employeeId: 1,
      },
      {
        certificationType: "Management",
        certificationName: "PMP Certification",
        otherYear: "2021",
        otherLocation: "New York, USA",
        certificationExpireDate: "2024-11-30",
        certificationBody: "Project Management Institute",
        documents: null,
        employeeId: 1,
      },
    ];

    await Certification.bulkCreate(certify, { ignoreDuplicates: true });
    console.log("Certification Details successfully seeded!");

    // Seed Work Experience
    const workExperience = [
      {
        companyName: "ABC Corp",
        companyLocation: "Qatar",
        industry: "IT",
        designation: "Software Engineer",
        startDate: "2022-01-01",
        endDate: "2023-01-01",
        employeeId: 1,
      },
      {
        companyName: "ABC Corp",
        companyLocation: "Qatar",
        industry: "IT",
        designation: "Software Engineer",
        startDate: "2022-01-01",
        endDate: "2023-01-01",
        employeeId: 1,
      },
      {
        companyName: "ABC Corp",
        companyLocation: "Qatar",
        industry: "IT",
        designation: "Software Engineer",
        startDate: "2022-01-01",
        endDate: "2023-01-01",
        employeeId: 1,
      },
    ];

    await WorkExperience.bulkCreate(workExperience, { ignoreDuplicates: true });
    console.log("Work experience successfully seeded!");

    // Seed Employee Contracts
    const employeeContractsHR = [
      {
        contractType: "Permanent",
        contractNumber: "EA/10/1011",
        contractAttachment: null,
        contractStartDate: "2025-01-01",
        contractEndDate: "2025-12-31",
        contractStatus: "Active",
        employeeId: 1,
      },
      {
        contractType: "Permanent",
        contractNumber: "EA/10/2022",
        contractAttachment: null,
        contractStartDate: "2025-01-01",
        contractEndDate: "2025-12-31",
        contractStatus: "Active",
        employeeId: 2,
      },
      {
        contractType: "Permanent",
        contractNumber: "EA/10/2023",
        contractAttachment: null,
        contractStartDate: "2025-01-01",
        contractEndDate: "2025-12-31",
        contractStatus: "Active",
        employeeId: 3,
      },
      {
        contractType: "Permanent",
        contractNumber: "EA/10/2024",
        contractAttachment: null,
        contractStartDate: "2025-01-01",
        contractEndDate: "2025-12-31",
        contractStatus: "Active",
        employeeId: 4,
      },
      {
        contractType: "Permanent",
        contractNumber: "EA/10/2025",
        contractAttachment: null,
        contractStartDate: "2025-01-01",
        contractEndDate: "2025-12-31",
        contractStatus: "Active",
        employeeId: 5,
      },
    ];

    await EmployeeContractModel.bulkCreate(employeeContractsHR, {
      ignoreDuplicates: true,
    });
    console.log("Employee contracts successfully seeded!");

    // Seed Job Posting Data
    const jobPostoingDetails = [
      {
        jobCode: "JOB-2510-FT-DOH-0001",
        jobTitle: "Light Driver",
        jobDescription: "Handle the light vehicles for the delivery company",
        location: "Doha, Qatar",
        salary: 1700,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
      {
        jobCode: "JOB-2510-FT-DOH-0002",
        jobTitle: "Bus Driver",
        jobDescription: "Handle the buses for the delivery company",
        location: "Doha, Qatar",
        salary: 2000,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
      {
        jobCode: "JOB-2510-FT-DOH-0003",
        jobTitle: "Mini Excavator Operator",
        jobDescription: "Handle the mini excavators for the delivery company",
        location: "Doha, Qatar",
        salary: 2000,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
      {
        jobCode: "JOB-2510-FT-DOH-0004",
        jobTitle: "Boom Truck Operator",
        jobDescription: "Handle the boom trucks for the delivery company",
        location: "Doha, Qatar",
        salary: 2000,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
      {
        jobCode: "JOB-2510-FT-DOH-0005",
        jobTitle: "Forklift Operator",
        jobDescription: "Handle the forklift for the delivery company",
        location: "Doha, Qatar",
        salary: 1800,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
      {
        jobCode: "JOB-2510-FT-DOH-0006",
        jobTitle: "Mobile Crane Operator",
        jobDescription: "Handle the mobile crane for the delivery company",
        location: "Doha, Qatar",
        salary: 4000,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
      {
        jobCode: "JOB-2510-FT-DOH-0007",
        jobTitle: "Skid Loader Operator",
        jobDescription: "Handle the skid loader for the delivery company",
        location: "Doha, Qatar",
        salary: 1700,
        postedAt: "2025-10-25",
        expiresAt: "2025-10-31",
        jobType: "Full-time",
        approvalStatus: "approved",
        responsibilities: [
          "Deliver packages",
          "Follow traffic rules",
          "Maintain safety",
        ],
        keyRequirements: [
          "Driving license",
          "Valid insurance",
          "Clean driving record",
        ],
        qualifications: ["Valid driving license", "Clean driving record"],
      },
    ];

    await JobPosting.bulkCreate(jobPostoingDetails, { ignoreDuplicates: true });
    console.log("Job Posting Details successfully seeded!");

    // Seed Employee Contract Template Data
    const contractTemplateDetails = [
      {
        templateName: "Light Driver Contract Template",
        jobTitle: "Light Driver",
        contractPeriod: "three months",
        autoRenewal: true,
        autoRenewalPeriod: "three months",
        noticeRequirement: "30 days",
        basicSalary: 1700.0,
        fixedAllowance: 200.0,
        accommodationProvided: true,
        accommodationAmount: 300.0,
        foodProvided: true,
        foodAmount: 150.0,
        transportationProvided: true,
        transportationAmount: 100.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 15.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "one month",
        terminationNoticeEmployee: "one month",
        earlyTerminationCharges:
          "Employee shall pay one month basic salary if leaving before contract completion",
        increment: 100.0,
        incrementPeriod: "after completion of 3 months",
        additionalTerms:
          "Employee must maintain valid driving license throughout employment period",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
      {
        templateName: "Bus Driver Contract Template",
        jobTitle: "Bus Driver",
        contractPeriod: "six months",
        autoRenewal: true,
        autoRenewalPeriod: "six months",
        noticeRequirement: "30 days",
        basicSalary: 2000.0,
        fixedAllowance: 250.0,
        accommodationProvided: true,
        accommodationAmount: 350.0,
        foodProvided: true,
        foodAmount: 150.0,
        transportationProvided: true,
        transportationAmount: 100.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 18.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "one month",
        terminationNoticeEmployee: "one month",
        earlyTerminationCharges:
          "Employee shall pay one month basic salary if leaving before contract completion",
        increment: 150.0,
        incrementPeriod: "after completion of 6 months",
        additionalTerms:
          "Employee must maintain valid bus driving license and clean driving record",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
      {
        templateName: "Mini Excavator Operator Contract Template",
        jobTitle: "Mini Excavator Operator",
        contractPeriod: "six months",
        autoRenewal: true,
        autoRenewalPeriod: "six months",
        noticeRequirement: "30 days",
        basicSalary: 2000.0,
        fixedAllowance: 250.0,
        accommodationProvided: true,
        accommodationAmount: 350.0,
        foodProvided: true,
        foodAmount: 150.0,
        transportationProvided: true,
        transportationAmount: 100.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 18.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "one month",
        terminationNoticeEmployee: "one month",
        earlyTerminationCharges:
          "Employee shall pay one month basic salary if leaving before contract completion",
        increment: 150.0,
        incrementPeriod: "after completion of 6 months",
        additionalTerms:
          "Employee must maintain valid excavator operating license and safety certifications",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
      {
        templateName: "Boom Truck Operator Contract Template",
        jobTitle: "Boom Truck Operator",
        contractPeriod: "six months",
        autoRenewal: true,
        autoRenewalPeriod: "six months",
        noticeRequirement: "30 days",
        basicSalary: 2000.0,
        fixedAllowance: 250.0,
        accommodationProvided: true,
        accommodationAmount: 350.0,
        foodProvided: true,
        foodAmount: 150.0,
        transportationProvided: true,
        transportationAmount: 100.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 18.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "one month",
        terminationNoticeEmployee: "one month",
        earlyTerminationCharges:
          "Employee shall pay one month basic salary if leaving before contract completion",
        increment: 150.0,
        incrementPeriod: "after completion of 6 months",
        additionalTerms:
          "Employee must maintain valid boom truck operating license and safety certifications",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
      {
        templateName: "Forklift Operator Contract Template",
        jobTitle: "Forklift Operator",
        contractPeriod: "three months",
        autoRenewal: true,
        autoRenewalPeriod: "three months",
        noticeRequirement: "30 days",
        basicSalary: 1800.0,
        fixedAllowance: 200.0,
        accommodationProvided: true,
        accommodationAmount: 300.0,
        foodProvided: true,
        foodAmount: 150.0,
        transportationProvided: true,
        transportationAmount: 100.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 16.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "one month",
        terminationNoticeEmployee: "one month",
        earlyTerminationCharges:
          "Employee shall pay one month basic salary if leaving before contract completion",
        increment: 100.0,
        incrementPeriod: "after completion of 3 months",
        additionalTerms:
          "Employee must maintain valid forklift operating license and safety certifications",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
      {
        templateName: "Mobile Crane Operator Contract Template",
        jobTitle: "Mobile Crane Operator",
        contractPeriod: "one year",
        autoRenewal: true,
        autoRenewalPeriod: "one year",
        noticeRequirement: "60 days",
        basicSalary: 4000.0,
        fixedAllowance: 500.0,
        accommodationProvided: true,
        accommodationAmount: 500.0,
        foodProvided: true,
        foodAmount: 200.0,
        transportationProvided: true,
        transportationAmount: 150.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 35.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "two months",
        terminationNoticeEmployee: "two months",
        earlyTerminationCharges:
          "Employee shall pay two months basic salary if leaving before contract completion",
        increment: 300.0,
        incrementPeriod: "after completion of 1 year",
        additionalTerms:
          "Employee must maintain valid mobile crane operating license and specialized safety certifications. Regular safety training mandatory.",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
      {
        templateName: "Skid Loader Operator Contract Template",
        jobTitle: "Skid Loader Operator",
        contractPeriod: "three months",
        autoRenewal: true,
        autoRenewalPeriod: "three months",
        noticeRequirement: "30 days",
        basicSalary: 1700.0,
        fixedAllowance: 200.0,
        accommodationProvided: true,
        accommodationAmount: 300.0,
        foodProvided: true,
        foodAmount: 150.0,
        transportationProvided: true,
        transportationAmount: 100.0,
        workingDaysPerMonth: 26,
        workingHoursPerDay: 10,
        overtimeRate: 15.0,
        workingPermitRequired: true,
        workingPermitPeriod: "one year",
        terminationNoticeCompany: "one month",
        terminationNoticeEmployee: "one month",
        earlyTerminationCharges:
          "Employee shall pay one month basic salary if leaving before contract completion",
        increment: 100.0,
        incrementPeriod: "after completion of 3 months",
        additionalTerms:
          "Employee must maintain valid skid loader operating license and safety certifications",
        companyName: "Auto Xpert Trading and Services W.L.L",
        companyAddress: "Doha, Qatar",
        companyContact: "+974 XXXX XXXX",
        signingAuthorityName: "Sajee Kumaran Wickneswara",
        signingAuthorityPosition: "Finance Manager",
        isActive: true,
      },
    ];

    await EmployeeContractTemplateModel.bulkCreate(contractTemplateDetails, {
      ignoreDuplicates: true,
    });
    console.log("Employee Contract Template Details successfully seeded!");

    console.log(
      "Human Resources Database seeded successfully with ITEQ Solution data.",
    );
  } catch (error) {
    console.error("Error inserting initial data:", error);
  }
};

module.exports = seedDatabase;
