const bcrypt = require("bcrypt");
const sequelize = require("../config/dbSync");
const Employee = require("../models/LeadModel").associations.salesPersonEmployee.target;
const Lead = require("../models/LeadModel");
const Prospect = require("../models/ProspectModel");
const SalesPipeline = require("../models/SalesPipelineModel");
const Form = require("../models/FormModel");
const FormField = require("../models/FormFieldModel");
const PipelineStage = require("../models/PipelineStageModel");
const TextFieldType = require("../models/TextFieldTypeModel");

const seedDatabase = async (syncOption = { alter: true }) => {
  try {
    // Sync database
    await sequelize.sync(syncOption);
    console.log(`Database synced with ${JSON.stringify(syncOption)}`);

    //-----------------------------------------------------Sales CRM Module Seeds------------------------------------------------------------

    // Seed data for 1st employee
    const sampleEmployees = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0001",
          fullNameEnglish: "John Doe",
          fullNameArabic: "جون دو",
          qidNumber: 123456,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "john.doe@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "John Doe",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 23121,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC123456789",
          issuingAuthority: "Qatar Health Ministry",
          expireDate: "2025-12-31",
          knownMedicalConditions: "None",
          allergies: "Peanuts",
          notesOrRemarks: "Requires annual check-up",
          policyNumber: "POL123456",
          coverageDetails: "Comprehensive medical and dental coverage",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Doha Insurance",
          additionalPolicyDetails: "Includes emergency evacuation",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Forklift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-06",
          gatePassNumber: "GP789045",
          gatePassLocation: "Doha",
          gateAccessNo: "1, 12",
          appHashNumber: "App808706",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ799979",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Office",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 6,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees, { ignoreDuplicates: true, hooks: false });
    console.log("Employees 1 successfully seeded!");

    // Seed data for 2nd employee
    const sampleEmployees2 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0002",
          fullNameEnglish: "Alan Taylor",
          fullNameArabic: "جون دو",
          qidNumber: 232532,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "alan.taylor@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "John Doe",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees2, { ignoreDuplicates: true, hooks: false });
    console.log("Employees 2 successfully seeded!");

    // Seed data for 3rd employee
    const sampleEmployees3 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0003",
          fullNameEnglish: "Mathew Jackson",
          fullNameArabic: "جون دو",
          qidNumber: 785432,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "mathew.jackson@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "Mathew Jackson",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees3, { ignoreDuplicates: true, hooks: false });
    console.log("Employees 3 successfully seeded!");

    // Seed data for 4th employee
    const sampleEmployees4 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0004",
          fullNameEnglish: "William Smith",
          fullNameArabic: "جون دو",
          qidNumber: 678686,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "william.smith@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "William Smith",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees4, { ignoreDuplicates: true, hooks: false });
    console.log("Employees 4 successfully seeded!");

    // Seed data for 5th employee
    const sampleEmployees5 = [
      {
        personalDetails: {
          profileImage: "https://example.com/profile1.jpg",
          employeeNo: "AX-0005",
          fullNameEnglish: "Thomas Anderson",
          fullNameArabic: "جون دو",
          qidNumber: 7599457,
          passportNumber: "P1234567",
          qidExpireDate: "2026-12-31",
          passportExpireDate: "2026-12-31",
          recruitementType: "Local",
          visaNumber: "V1234567",
          nationality: "American",
          mobileNumber: "+97467895432",
          email: "thomas.anderson@example.com",
          gender: "Male",
          dateOfBirth: "1990-01-01",
          currentAddress: "123 Main St, City, Country",
          permanentAddress: "456 Permanent Rd, City, Country",
          maritalStatus: "Single",
        },
        drivingLicenseDetails: {
          isAvailableLicense: true,
          drivingLicenseCopy: null,
          licenseNumber: "DL12345",
          firstIssueDate: "2022-01-01",
          licenseExpireDate: "2023-01-01",
          licenseCategory: ["Excavator", "Crane"],
          licenseNotes: ["Glasses", "Automatic"],
        },
        bankDetails: {
          bankName: "ABC Bank",
          accountHolderName: "William Smith",
          accountNumber: 1234567890123456,
          branchName: "Main Branch",
          IBAN: "QA1234567890123456789",
          swiftCode: 1232333,
          shortCode: 12345,
        },
        sponserDetails: {
          sponserName: "Sponsored by Outside",
          employeeContractCopy: null,
          contractExpireDate: "2025-12-31",
          companyCRCopyExpireDate: "2025-12-31",
          computerCardCopy: null,
          computerCardExpireDate: "2025-12-31",
          NOC: null,
          companyCRCopy: null,
        },
        documentDetails: {
          image: null,
          copyOfQID: null,
          copyOfPassport: null,
          resume: null,
          qualificationCertificate: null,
          otherDocuments: null,
        },
        insuranceDetails: {
          healthCardNumber: "HC987654321",
          issuingAuthority: "Hamad Medical Corporation",
          expireDate: "2025-12-31",
          knownMedicalConditions: "Hypertension",
          allergies: "None",
          notesOrRemarks: "Requires monthly monitoring",
          policyNumber: "POL789123",
          coverageDetails: "Basic medical coverage, excludes dental",
          compensationExpireDate: "2026-12-31",
          insuranceProvider: "Al Koot Insurance",
          additionalPolicyDetails: "Excludes pre-existing conditions",
          attachments: null,
        },
        fleetDetails: {
          operatorType: "Manlift Operator",
          equipmentDetails: "LAP-121121221 - Heavy Type",
          month: "2025-07",
          gatePassNumber: "GP123456",
          gatePassLocation: "RL",
          gateAccessNo: "1, 14",
          appHashNumber: "App543555",
          gatePassIssueDate: "2023-01-01",
          gatePassExpireDate: "2025-12-31",
          gatePassAttachment: null,
          gatePassExpireStatus: "Valid",
          fleetStatus: "Active",
        },
        trainingCertificationsDetails: {
          trainingTitle: "Certified Trainer",
          issueDate: "2023-01-01",
          expiryDate: "2023-01-06",
          idIqamaNo: "IQ335655",
          companyName: "Auto-Expert",
          description: "Training Certification",
          certifiedAs: "James Dafoe",
          trainingCertificate: null,
        },
        otherDetails: {
          dateOfJoin: "2023-01-01",
          designation: "Software Engineer",
          employeeType: "Operation",
          status: "Active",
          workPlace: "Qatar",
          departmentName: "IT",
          annualLeaveCount: 10,
          destinationCountry: "Qatar",
        },
        completionStatuses: {
          bank: "Not Available Now",
          other: "Not Available Now",
          career: "Yes",
          family: "Yes",
          license: "No",
          payroll: "No",
          sponsor: "Not Available Now",
          personal: "Yes",
          documents: "No",
          insurance: "Yes",
          fleet: "Yes",
          training: "Yes",
          contract: "Yes",
        },
      },
    ];

    await Employee.bulkCreate(sampleEmployees5, { ignoreDuplicates: true, hooks: false });
    console.log("Employees 5 successfully seeded!");

    // Insert default text field types
    const textFieldTypes = [
      { type_name: "Text", type_value: "text" },
      { type_name: "Phone Number", type_value: "number" },
      { type_name: "Email", type_value: "email" },
      { type_name: "Date", type_value: "date" },
      { type_name: "Currency", type_value: "text" },
    ];
    await TextFieldType.bulkCreate(textFieldTypes, { ignoreDuplicates: true });

    console.log("Sales CRM Database seeded successfully with ITEQ Solution data.");
  } catch (error) {
    console.error("Error inserting initial data:", error);
  }
};

module.exports = seedDatabase;
